language: objective-c
osx_image: xcode11.5

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    
addons:
  ssh_known_hosts: github.com

notifications:
  email: false
  
before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/LFLDarkModeDemo.xcworkspace -scheme LFLDarkModeDemo_Example -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug | xcpretty -c

  - echo Clean DerivedData
  - rm -rf ~/Library/Developer/Xcode/DerivedData/
  - mkdir DerivedData

